# Generated by Django 2.1.4 on 2018-12-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('ctext', models.CharField(max_length=500)),
                ('createtime', models.TimeField()),
                ('nid', models.IntegerField()),
                ('uid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.DecimalField(decimal_places=10, max_digits=14)),
                ('lng', models.DecimalField(decimal_places=10, max_digits=14)),
                ('radius', models.FloatField()),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('onfriend', models.IntegerField()),
                ('tid', models.IntegerField()),
                ('sid', models.IntegerField()),
                ('uid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friender', models.IntegerField()),
                ('friendee', models.IntegerField()),
                ('comfirmed', models.BooleanField()),
                ('createtime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('ltime', models.TimeField()),
                ('lat', models.DecimalField(decimal_places=10, max_digits=14)),
                ('lng', models.DecimalField(decimal_places=10, max_digits=14)),
                ('sid', models.IntegerField()),
                ('operation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('ntext', models.CharField(max_length=500)),
                ('lat', models.DecimalField(decimal_places=10, max_digits=14)),
                ('lng', models.DecimalField(decimal_places=10, max_digits=14)),
                ('radius', models.FloatField()),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('scheduletype', models.IntegerField()),
                ('visibility', models.IntegerField()),
                ('createtime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='NoteTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.IntegerField()),
                ('tid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('stext', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('ttext', models.CharField(max_length=50)),
            ],
        ),
    ]
