# Generated by Django 2.1.4 on 2018-12-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='createtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='filter',
            name='endtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='filter',
            name='starttime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='friend',
            name='createtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='ltime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='createtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='endtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='starttime',
            field=models.DateTimeField(),
        ),
    ]
