# Generated by Django 2.1.4 on 2018-12-08 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20181205_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='nid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Note'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filter',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.State'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Tag'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='location',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.State'),
        ),
        migrations.AlterField(
            model_name='location',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notetag',
            name='nid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Note'),
        ),
        migrations.AlterField(
            model_name='notetag',
            name='tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Tag'),
        ),
        migrations.AlterField(
            model_name='state',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
