# Generated by Django 2.1.4 on 2018-12-08 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20181208_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='comfirmed',
            new_name='confirmed',
        ),
    ]
