# Generated by Django 2.1.4 on 2018-12-09 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20181208_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='sid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='filter',
            name='tid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='friend',
            name='friendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ufriendee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friend',
            name='friender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ufriender', to=settings.AUTH_USER_MODEL),
        ),
    ]
