# Generated by Django 2.1.4 on 2018-12-09 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20181209_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='sid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainsite.State'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='tid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainsite.Tag'),
        ),
    ]
